[pytest]
addopts = -vv -s --tb=short --alluredir=allure-results --reruns 2 --reruns-delay 3
testpaths = src

python_files = test_*.py steps_*.py *_steps.py

markers =
    smoke: smoke tests
    regression: regression tests