[pytest]
addopts = -vv -s --tb=short --alluredir=allure-results --screenshot only-on-failure --full-page-screenshot
testpaths = src

python_files = test_*.py steps_*.py *_steps.py

markers =
    smoke: smoke tests
    regression: regression tests