[pytest]
# 1. Increase verbosity and point to where your test suites actually live
addopts = -vv -s --tb=short --alluredir=allure-results
testpaths = src

python_files = test_*.py steps_*.py *_steps.py

markers =
    smoke: smoke tests
    regression: regression tests

asyncio_mode = strict