from dataclasses import dataclass

@dataclass
class CargoInsuredInformationParams:
    business_insured_name: str = ""
    DBA_trade_name: str = ""
    insured_ICC_docket_number_MC: str = ""
    type_of_entity: str = ""
    address_street1: str = ""
    address_street2: str = ""
    address_city: str = ""
    address_state: str = ""
    address_zip: str = ""
    new_venture: str = ""
    year_established: str = ""
    type_of_company_carrier: str = ""
    filings_required: str = ""
    include_all_owned_operated_units: str = ""
    years_in_business: str = ""
    federal_tax_ID_EIN: str = ""
    email_address: str = ""
    phone_number: str = ""
    garaging_address_street1: str = ""
    garaging_address_street2: str = ""
    garaging_address_city: str = ""
    garaging_address_state: str = ""
    garaging_address_zip: str = ""
